---
title: "Picrust2_Plot"
author:
- name: Yendi E. Navarro-Noya
  affiliation: Laboratory of Biotic Interactions, Centro de Investigación en Ciencias
    Biológicas, Universidad Autónoma de Tlaxcala, Tlaxcala, Mexico
  email: yendiebenezer.navarro.n@uatx.mx
- name: Stephanie Hereira-Pacheco
  affiliation: Laboratory of Soil Ecology, CINVESTAV-IPN, Ciudad de México, Mexico
  email: shereirap@gmail.com
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  html_document:
    theme: flatly
    highlight: tango
    toc: yes
    toc_depth: 2
    toc_float: yes
    df_print: paged
---

# VIII. PICRUST2 PLOT

### Loading libraries

```{r, warning=F, message=F}
library(ComplexHeatmap)
library(tidyverse)
library(circlize)
library(viridis)
library(RColorBrewer)
library(cowplot)
```

### Loadings files

```{r, warning=FALSE, message=FALSE}

aldex_all_dif_soil<- read_tsv( "../Data/aldex_Soil_picrust.tsv") %>% arrange(diff.btw)
aldex_all_dif_Treatment<- read_tsv( "../Data/aldex_Treatment_picrust.tsv")%>% arrange(diff.btw)
aldex_all_dif_Stage_vvsf<- read_tsv( "../Data/aldex_Stage_vvsf_picrust.tsv")%>% arrange(diff.btw)
aldex_all_dif_Stage_vvsg<- read_tsv( "../Data/aldex_Stage_vvsg_picrust.tsv")%>% arrange(diff.btw)
aldex_all_dif_Stage_fvsg<- read_tsv( "../Data/aldex_Stage_fvsg_picrust.tsv")%>% arrange(diff.btw)


```

### Formatting files

```{r, fig.height = 5, fig.width = 2.7, fig.align = "center"}
a<-aldex_all_dif_soil %>%  mutate(Dif = case_when(
  diff.btw < 0 ~ "RH",
  diff.btw > 0  ~ "BS")) %>% group_by(Dif) %>%
  summarise(n = n()) %>% 
  mutate(freq = round(n / sum(n)*100)) %>% mutate(type = "BS vs Rh \n  Soil")

b<-aldex_all_dif_Treatment %>%  mutate(Dif = case_when(
  diff.btw < 0 ~ "CA",
  diff.btw > 0  ~ "CP")) %>% group_by(Dif) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n)*100))%>% mutate(type = "CA vs CP \n Practice")

c<-aldex_all_dif_Stage_vvsf %>%  mutate(Dif = case_when(
  diff.btw < 0 ~ "V",
  diff.btw > 0  ~ "F")) %>% group_by(Dif) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n)*100))%>% mutate(type = "V vs F \n  Stage")

d<-aldex_all_dif_Stage_vvsg %>%  mutate(Dif = case_when(
  diff.btw < 0 ~ "V",
  diff.btw > 0  ~ "G")) %>% group_by(Dif) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n)*100))%>% mutate(type = "V vs G \n  Stage")

e<-aldex_all_dif_Stage_fvsg%>%  mutate(Dif = case_when(
  diff.btw < 0 ~ "F",
  diff.btw > 0  ~ "G")) %>% group_by(Dif) %>%
  summarise(n = n()) %>%
  mutate(freq = round(n / sum(n)*100))%>% mutate(type = "F vs G \n Stage")

#joining all files
graph<- rbind(a,b,c,d,e) %>%mutate(
  freq2= paste(freq,"%", sep = ""))

#setting labels (sum of n by type)

label2<- paste("n=",graph$n[1]+graph$n[2], sep = "")
label1<- paste("n=",graph$n[3]+graph$n[4], sep = "")
label5<- paste("n=",graph$n[5]+graph$n[6], sep = "")
label4<- paste("n=",graph$n[7]+graph$n[8], sep = "")
label3<- paste("n=",graph$n[9]+graph$n[10], sep = "")


head(graph)
```

### Barplot

```{r, fig.height = 5, fig.width = 5.5, fig.align = "center", warning=FALSE, message=FALSE}

#annotation to facets

ann_text<-data.frame(type=c("BS vs Rh \n  Soil", "CA vs CP \n Practice",
                            "F vs G \n Stage","V vs F \n  Stage", "V vs G \n  Stage"),
                     n=c(200,200,120, 250, 250),
                     Dif=c("BS","CA","G", "F", "V"),
                     label=c(label2, label1, label3, label5, label4))
#plot

graphs2=graph %>%  ggplot(aes(x = type, y = n, fill = Dif))+ geom_bar(stat = "identity",color="black")+facet_wrap(vars(type), scales = "free_x", ncol = 5)+
  ylab("No. of EC number differentially abundant")+
  geom_text(data = graph, aes(label=freq2),position = position_stack(vjust = 0.5),  size=4, color = "gold3", fontface="bold")+
  geom_text(data = ann_text,label=ann_text$label)  + theme_bw()+
  theme(panel.spacing=unit(1,"lines"), 
        strip.text.x = element_text(size = 12),
        axis.text.y =  element_text(colour = "black", size = 14),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(), 
        axis.ticks.x=element_blank(), 
        axis.title.y = element_text(size = 14), 
        legend.title = element_text(size = 12),
        legend.text = element_text(size=12), 
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.direction = "vertical" ,
        legend.position = "none")+scale_fill_manual(
          values = c("darkgoldenrod4",
                     "#212F3D", "#839192","darkolivegreen3",
                     "darkolivegreen",
                     "#365238", "darkolivegreen1"))
   graphs2

#pdf("fig_picrust_ECnumber.pdf", width=5.5, height=5)
#print(graphs2)
#dev.off()
```